def build_lists(m, n):
    L1 = [0]
    L2 = [0]
    for i in range(1, m + 1):
        L1.append(i)
    if len(L1) > 1:
        L1[1] = 1

    if n > 1:
        L2.append(1)
    for i in range(2, n + 1):
        x = L2[i - 1] + m
        L2.append(x)

    return L1, L2

#generated by chatGPT
def compute_sum_matrix(L1, L2):
    return [[a + b for b in L2] for a in L1]

# Example
m, n = 10, 10
L1, L2 = build_lists(m, n)
sum_matrix = compute_sum_matrix(L1, L2)

# Print as a neat matrix (no brackets)
for row in sum_matrix:
    print(*row)





